### ISSUE TITLE
Blockbench is compatible (with a caveat)

### ISSUE THREAD

**Issue by NetImmerse** [vxiiduu/VxKex#135]
Seeing the Chromium/Electron update, i've tried out a newer version of a low-poly 3d modeling software called Blockbench, and it actually works (more specifically, the full version):
![2024-03-18 22_00_38-](https://github.com/vxiiduu/VxKex/assets/21229472/891193d9-7baa-4ea6-b3fb-72b50725731d)
But the portable version doesn't, it just launches the process and it stays as a blank window without any changes in used memory.
Not like it's a big issue because the installed version works flawlessly, but the logs are attached: 
[Logs.zip](https://github.com/vxiiduu/VxKex/files/14641514/Logs.zip)

This project is something of another world, i kneel

**Comment by vxiiduu** [comment]
Thanks for the report.

I can't guarantee that this bug with the portable version will be fixed, because it surprisingly turned out to be very hard to debug. But glad it's working for you with the non-portable version.

Btw, you can decompress the portable exe with 7-zip and extract the folder with the app itself, in case you don't want to install but still want to be able to run the program with VxKex.

**Comment by NetImmerse** [comment]
No longer an issue since version 1.1.1.1375, portable version works as good as installed version.

vxiiduu-sama i kneel

**Comment by i486** [comment]
@MypkaMax

Latest version appears to be working fine

![image](https://github.com/vxiiduu/VxKex/assets/625325/afb691d8-ea4e-431b-b266-4027d32d4ee2)

![image](https://github.com/vxiiduu/VxKex/assets/625325/958d98e9-f98d-4d56-b7a5-59a4e511f386)

**Comment by MypkaMax** [comment]
Is this the desktop version or the portable version?

**Comment by MypkaMax** [comment]
Also, have any of you experienced icons flashing to blank and back to normal while updating BlockBench? This is not related to VxKex, this happened on my machine even before I installed VxKex.
