### ISSUE TITLE
New version of qBittorent (4.4.3 QT6) stopped working with VxKex. Only 4.4.2 QT6 works with VxKex.

### ISSUE THREAD

**Issue by MasterSlenderTR** [vxiiduu/VxKex#17]
![2](https://user-images.githubusercontent.com/50411937/169855677-b6257474-19a7-4e2d-aafe-1af172743a1a.png)
![1](https://user-images.githubusercontent.com/50411937/169855682-716afed4-1a62-4b2f-8597-920e9707f431.png)

**Comment by sydia1103** [comment]
You are using the latest version built from source?

**Comment by MasterSlenderTR** [comment]
No, I'm using 0.0.2, I don't know how to compile from the source.

**Comment by Darthagnon** [comment]
[Here is a compatibility hack thread on the Qt forums for Qt 6.3](https://forum.qt.io/topic/133002/qt-creator-6-0-1-and-qt-6-2-2-running-on-windows-7). From what I've heard, it's mainly Qt6.3 that has dropped support for pre-Win10. PCSX2 has a similar problem, but [there are Qt6.2.2 compatibility builds available here](https://github.com/dio-gh/pcsx2/). 

A lot of stuff is built off Qt, so this problem is going to become more widespread as time goes on.

**Comment by vxiiduu** [comment]
This issue has been fixed - code will be uploaded and new installers uploaded
Thanks for reporting this issue

![image](https://user-images.githubusercontent.com/73044267/185731933-50809655-16f0-4085-bdf8-7a399d478bf0.png)
