### ISSUE TITLE
Chromium 110 fails to launch even with VxKex with missing KERNEL32 function "GetProcessMitigationPolicy"

### ISSUE THREAD

**Issue by Smu1zel** [vxiiduu/VxKex#43]
Starting with Chromium 110, Google broke Windows 7 (and possibly 8.1) support. I tried running it with VxKex 0.0.3 and the result doesn't change. This is the error that is prompted.
![image](https://user-images.githubusercontent.com/96768305/202871746-9f1a45de-e70a-4b0a-8ad3-2702f42652e0.png)

I don't expect this to be fixed right away, with the rewrite and all that. I just wanted to bring attention to the issue in hopes that Chrome can continue to live on 7 and 8.1 systems in the future.
https://chromium.cypress.io/win/canary/110.0.5428.0
Here's the build tested
EDIT: Going by some reports, it seems to still run on 8.1, but you have to disable the sandbox with --no-sandbox.

**Comment by Lanurence666** [comment]
In fact, for Chromium 110.0.5425.0, it still works on Windows 7. Since 110.0.5426.0, it started to drop support.
So if we can compare the two versions of chromium said above, the solution maybe appears.
Source: https://www.betaarchive.com/forum/viewtopic.php?t=44218
![2109EBBC-C676-4A70-B587-E2ECF10DB092](https://user-images.githubusercontent.com/59821642/213377991-7b4b47cc-8690-4157-8de7-da3d26852718.png)

**Comment by Smu1zel** [comment]
> In fact, for Chromium 110.0.5425.0, it still works on Windows 7. Since 110.0.5426.0, it started to drop support. So if we can compare the two versions of chromium said above, the solution maybe appears. Source: https://www.betaarchive.com/forum/viewtopic.php?t=44218 ![2109EBBC-C676-4A70-B587-E2ECF10DB092](https://user-images.githubusercontent.com/59821642/213377991-7b4b47cc-8690-4157-8de7-da3d26852718.png)

I looked at that and someone ironically seems to have gotten it to function on Vista.
https://msfn.org/board/topic/181612-wip-windows-vista-extended-kernel/?do=findComment&comment=1233778

There was also this Reddit comment that said it still worked for them on 7 and that they had the 7 ESU updates installed. Though I can't confirm this.

**Comment by Lanurence666** [comment]
> There was also this Reddit comment that said it still worked for them on 7 and that they had the 7 ESU updates installed. Though I can't confirm this.
 How do they achieve that?

**Comment by Smu1zel** [comment]
> > There was also this Reddit comment that said it still worked for them on 7 and that they had the 7 ESU updates installed. Though I can't confirm this.
> 
> How do they achieve that?

Don't have a clue, wasn't any screenshots or anything. Could've been a older Canary build that still worked.

**Comment by Lanurence666** [comment]
Well, there is little difference between vista and 7. So we can supplement some functions that the Vista extended kernel implemented to make the latest Chromium work. That is what the Vista Extended kernel does. 
However, we don't know what function the kernel implements, and what function VxKex does not have currently. We should let the author to answer these questions, maybe.

**Comment by Saswat2005** [comment]
No worries. I will be making an extended kernel for that. Patched files will be given.

**Comment by sk8rthug** [comment]
> There was also this Reddit comment that said it still worked for them on 7 and that they had the 7 ESU updates installed. Though I can't confirm this.

No, it doesn't work with ESU updates. I have them installed using BypassESU - the same error.

**Comment by Smu1zel** [comment]
> > There was also this Reddit comment that said it still worked for them on 7 and that they had the 7 ESU updates installed. Though I can't confirm this.
> 
> No, it doesn't work with ESU updates. I have them installed using BypassESU - the same error.

Yeah, as I figured.

**Comment by TiberiumFusion** [comment]
Just for hoots, this is as far as the current Chromium stable 112.0.5615.56 gets under VxKex 0.0.0.2

![uashdfguiohasdf](https://user-images.githubusercontent.com/6332277/230700274-0f60142c-bdce-4559-afa3-ee7a171ede8e.png)

[`DiscardVirtualMemory`](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-discardvirtualmemory) is since NT 6.3, so we're not even into Bugcrash 10 territory yet.

VxKex might not even need to implement `DiscardVirtualMemory` (if it's even possible). It seem like Chromium includes its own fallback to not use DiscardVirtualMemory on Bugcrash 10 RTM and instead use a standard `VirtualAlloc`. As long as Chromium supports non-redstone bugcrash for whatever bizarre reason, this can be exploited.
See [here](https://source.chromium.org/chromium/chromium/src/+/main:base/memory/discardable_shared_memory.cc;l=429?q=DiscardVirtualMemory) and [here](https://source.chromium.org/chromium/chromium/src/+/main:base/allocator/partition_allocator/page_allocator_internals_win.h;l=231?q=DiscardVirtualMemory).

An application specific hack that provides a shim DiscardVirtualMemory which always returns `ERROR_SUCCESS` would be enough to clear this hurdle and get on to the next one.

**Comment by Squall-Leonhart** [comment]
it's be better to implement discardvirtualmemory because this makes memory management more efficient,  take a look at chrome on windows 7 where the parent browser process eventually consumes 4GB's and crashes now thanks to the sandbox now being limited to 4GB containers.

**Comment by vxiiduu** [comment]
@Squall-Leonhart that problem is completely separate from DiscardVirtualMemory. In fact, DiscardVirtualMemory is properly implemented in VxKex.

@Smu1zel Chrome 110-125 (64 bit) works with VxKex. 32 bit version not yet.
