### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by dotexe1337** [vxiiduu/VxKex#5]
Many applications will just flat out not start with VxKex, regardless of "Report a different version of windows" or other settings. These applications will normally at least throw some kind of error like "Your OS version is not supported" or something. I tried to debug the issue but kind of hit a dead end.

![image](https://user-images.githubusercontent.com/41847745/161579296-34f1b724-8408-432f-a3da-777b8fe47936.png)

**Comment by vxiiduu** [comment]
After investigating, I've found that it usually occurs with native Windows (7) programs. Regedit is a simple example.
0xC000007B is NTSTATUS for "invalid image format". I suspect that one of the DllMain procedures might be returning FALSE for some reason, I'll look into it more when I've got time.

**Comment by dotexe1337** [comment]
The program I was trying to run in this case was the setup for Adobe Premiere Pro which normally requires Windows 10. I have also gotten the same error with some other programs too.

**Comment by vxiiduu** [comment]
I should also mention that any program that is cracked or has strong DRM (Microsoft products generally do NOT have strong DRM) is unlikely and probably never will work under VxKex because those types of programs use direct syscalls targeted for Windows 10. So modern adobe stuff, denuvo games etc. won't work anyway

**Comment by vxiiduu** [comment]
Update: I have isolated the issue, it seems to only happen when the executable file contains a "Bound Import Directory". It seems like I will simply have to add support for this PE data directory into VxKexLdr which is probably not going to be very difficult.
Do you mind going into CFF Explorer, opening your EXE file of interest and going to Nt Headers->Optional Header->Data Directories and checking if "Bound Import Directory RVA" contains something? If the number is 00000000, there is no Bound Import Directory, and otherwise there is one.

![image](https://user-images.githubusercontent.com/73044267/161724731-ca109e5d-3c11-49f1-afaa-371912a26c33.png)

**Comment by vxiiduu** [comment]
I've fixed the issue, try this (do a reinstall with this installer) [KexSetup.zip](https://github.com/vxiiduu/VxKex/files/8417732/KexSetup.zip) and see whether it solves the error.

**Comment by dotexe1337** [comment]
Yup, adobe set up opens now without that error, but the OS spoofing function doesn't work. I will make a separate issue for that.
